api_version = "2025-07"

[[extensions]]
name = "Restore Product from Backup"
handle = "restore-product-action"
type = "ui_extension"

  [[extensions.targeting]]
  module = "./src/RestoreProductDetail.jsx"
  target = "admin.product-details.action.render"
